# Generated by Django 4.0.3 on 2022-03-22 15:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.upload_to, verbose_name='Image')),
                ('gender', models.CharField(choices=[('op1', 'Male'), ('op2', 'Female')], default='op1', max_length=10)),
                ('age', models.CharField(choices=[('op1', '< 4 Years'), ('op2', '4 to 9 Years'), ('op3', '10 to 14 Years'), ('op4', '> 14 Years')], default='op3', max_length=100)),
                ('location', models.CharField(default='NO LOCATION', max_length=200)),
            ],
        ),
    ]
