# Generated by Django 4.0.3 on 2022-03-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='gender',
            field=models.CharField(choices=[('op1', 'Male'), ('op2', 'Female')], default=None, max_length=10),
        ),
    ]
